<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<PackageId>CameraMonitorSystem</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AForge.Video.DirectShow" Version="2.2.5" />
		<PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.27.0" />
		<PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
		<PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260627" />
		<PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
	</ItemGroup>

	<ItemGroup>
		<None Update="yolov8n.onnx">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>